### ISSUE TITLE
Dead Companies

### ISSUE THREAD

**Issue by azzamsa** [azzamsa/awesome-lisp-companies#1]
Please inform me about dead companies, so I can add description(or icon) to them in the list

**Comment by jsjolen** [comment]
Finland's Steel Bank Studios is dead (I don't think Nikodemus does anything with CL anymore)

**Comment by nikodemus** [comment]
Correct. My CL use if strictly recreational these days.

**Comment by azzamsa** [comment]
@nikodemus, wow, such a pleasure to have you here.

Sorry for asking, are you retired your self from programming or just move to other languages ?

Thank you, Nikodemus.

**Comment by azzamsa** [comment]
@jsjolen thank you, Jsjolen.

**Comment by nikodemus** [comment]
Oh, I'm programming all right, but I stopped being self employed and went to work for ZenRobotic Ltd.

**Comment by azzamsa** [comment]
@nikodemus That's great. Thank you for all your contribution to community. You inspired me too.

Have a nice day and Happy hacking.
