### ISSUE TITLE
Cognesys

### ISSUE THREAD

**Issue by rudolfochrist** [azzamsa/awesome-lisp-companies#4]
Hi there,

Cognesys is a Clojure shop nowadays (as least as far as I know).

Cheers,
Sebastian

**Comment by azzamsa** [comment]
I think you are right, [Software Engineer (m/w)](http://www.cognesys.de/wp-content/uploads/2017/04/Stellenausschreibung_Software_Engineer_24.04.2017.pdf)

**Comment by azzamsa** [comment]
Done, https://github.com/azzamsa/awesome-lisp-companies/commit/a71fef2f7786e4314ed0469467a710fa6116dcd9
