### ISSUE TITLE
consider adding companies using Clojure?

### ISSUE THREAD

**Issue by mark-watson** [azzamsa/awesome-lisp-companies#43]
I usually use Common Lisp, but my current job at Olive AI uses Clojure almost exclusively.

**Comment by Hexstream** [comment]
As someone who is deeply interested in Common Lisp and deeply uninterested in all other (alleged) lisps, I really hate when Common Lisp gets diluted with other (alleged) lisps.

Assuming this repo already lists Common Lisp companies only, how about renaming it to `awesome-common-lisp-companies`?

**Comment by azzamsa** [comment]
Hi, Mark.

I know you from your books. 
Sorry. But I make this repo only for Scheme and Common Lisp companies.

**Comment by mark-watson** [comment]
> Hi, Mark.
> 
> I know you from your books.
> Sorry. But I make this repo only for Scheme and Common Lisp companies.

I understand. Thanks for maintaining this list.

**Comment by kmatt** [comment]
As someone new to both CL (SBCL) and Clojure, I'm curious:

What separates other (alleged) Lisps from Scheme and Common Lisp in the context of this repo, given differences between Scheme and CL themselves?

**Comment by phoe** [comment]
If such is the policy of this repo, then it might be worth to link to a list of Clojure companies at https://clojure.org/community/companies which is open for PRs at https://github.com/clojure/clojure-site/blob/master/content/community/companies.adoc

**Comment by azzamsa** [comment]
If the same thing happened again. I will point them to your comment. thanks, @phoe.

**Comment by phoe** [comment]
OK - thanks. I still consider that it might be worth to add this link to the bottom of the list, so that people will be able to find it if they search the page for the string `Clojure`, but it's your decision at this point.

**Comment by azzamsa** [comment]
I decided not to. However Github search also include the string in the issues.
