### ISSUE TITLE
Add Black Brane Systems

### ISSUE THREAD

**Issue by phoe** [azzamsa/awesome-lisp-companies#47]
Black Brane Systems Inc. (@blackbranesys) provides services, languages, frameworks, and language compilers related to quantum computing.

Maybe @thephoeron can provide a better description than I, a complete newbie to all the quantum stuff, did above.

Possible links: 
* https://blackbrane.com/
* https://twitter.com/blackbranesys

**Comment by thephoeron** [comment]
Thanks for creating this issue, @phoe. Our slogan is "The Quantum Edge-Computing Company&trade;"

We're based in Toronto, Canada. Our entire software stack is written in Common Lisp, using LispWorks Enterprise, deploying to Linux, macOS, and Windows, for embedded, command-line, background process, cloud, automation, and integration applications services, supporting all components and models of edge-computing for quantum resources. We are a licensed Azure CSP and ISV, able to build, deploy, and manage applications of any scale in any region; we also support AWS and Digital Ocean.

Our technology portfolio includes:
- cloud-native, scalable, distributed Common Lisp images, clusters, and pipelines
- application-defined infrastructure automation
- proprietary domain-specific and general purpose quantum computing architectures
- quantum virtualization, a high-performance alternative to simulation and emulation based methods, using sampled quantum state-spaces and quantum chaos to recreate physical quantum effects lazily on classical hosts
- a universal quantum-cloud API and service integrating all quantum computing architectures across vendors and alternative quantum cloud services
- VQM Library, conforming and extended virtualizations of vendor-specific quantum architectures
- industry-leading quantum machine learning and quantum AI libraries and applications, incl.:
    - quantum neural networks
    - quantum ensemble methods
    - quantum proprioception and psychophysics
    - quantum problem-solving, planning, scheduling, and pathfinding
    - quantum collaborative learning and problem-solving
    - quantum genetic programming
    - quantum software and circuit synthesis (automatic programming)
    - quantum natural language understanding
    - explainable quantum models
- integrated, interactive, decentralized, learning quantum-compilation framework
- a comprehensive, modular, higher-order quantum object-model
- quantum, classical, and hybrid programming languages for:
    - general-purpose quantum-recursive/quantum-controlled programming
    - quantum logic programming
    - quantum meta-programming
    - quantum knowledge and domain engineering
    - quantum, classical, and hybrid circuit specification
    - quantum chemistry and material science
- and... a whole lot more

We're big on ethics, fully committed to building a safe, diverse, inclusive, positive, supportive, and collaborative community at the heart of the quantum computing industry. It's not going to be easy, but hey, solving impossible problems is what we do best.

**Comment by vindarel** [comment]
I fear Black Brane Sys is no more? https://cjelupton.wordpress.com/2022/01/31/project-goals-for-open-blackfire/

> There’s no denying, I went a little bit over the top with the closed-source, proprietary version of the Blackfire Framework under my now-defunct start-up, Black Brane Systems. For the new, open-source version, [Open-Blackfire](https://github.com/thephoeron/open-blackfire/)…
