### ISSUE TITLE
RIFFIT

### ISSUE THREAD

**Issue by josharmenta** [azzamsa/awesome-lisp-companies#54]
RIFFIT (riffitnow.com) is using Lisp and Scheme in production.

**Comment by vindarel** [comment]
Hi, thanks for the information. How do you know it? Is there a mention of Lisp on their website or somewhere else? And do you know *which* Lisp and *which* Scheme are they using?

**Comment by josharmenta** [comment]
I'm the one who is writing the algorithms :-). We use a combination of SIOD Scheme for natural language processing and SBCL and ECL for the core technology.

**Comment by vindarel** [comment]
Awesome. Thanks :)
