### ISSUE TITLE
add d-wave, somewrite, m-creations, secure outcomes

### ISSUE THREAD

**Issue by vindarel** [azzamsa/awesome-lisp-companies#6]
Hello, 

I got them by searching on recent lispjobs announces: https://gitlab.com/lisp-journey/lisp-journey.gitlab.io/blob/master/content/who.md

**Comment by azzamsa** [comment]
Hi vindarel, thank you for your interest.

I still have task  at hand, if you wish you can make appropriate PR according to this [guidleine](https://github.com/azzamsa/awesome-lisp-companies#guidelines-to-contribute)
