### ISSUE TITLE
I am no deader than usual

### ISSUE THREAD

**Issue by kennytilton** [azzamsa/awesome-lisp-companies#74]
Why am I listed as "disappeared as of 2018"? Did EC2 crash my site again?!

http://tiltonsalgebra.com/#

http://tiltontec.com/

ps. Thanks for the "funny guy"!

**Comment by vindarel** [comment]
Hi there mister Kenny Tilton, thanks for the heads up. Expect some questions of my part to close this issue :) (in short: how's your company doing, and how's Cells and its documentation doing ? :] )

**Comment by vindarel** [comment]
This website we had is blank: https://www.tilton-technology.com/

**Comment by kennytilton** [comment]
Algebra app, Common Lisp server driving qooxdoo ala Ruby Rails:

- promo site http://tiltontec.com/
- the app: http://tiltonsalgebra.com/#

ClojureScript consulting: https://www.linkedin.com/in/kennethtilton/?msgControlName=reply_to_sender&msgConversationId=2-Yjk0MzY3YTktNjQ3Yy01NGM5LWI5NGUtYWNlNzM5MDM0MTQwXzAwMA%3D%3D&msgOverlay=true

Open source:  https://github.com/kennytilton/matrix Includes JS and CLJS ports of Cells

Just starting a big push on promoting Matrix. This will include even more tutorials than you find under my github repo, and a straight reference section.
